#!/bin/bash
#####################################################################################
#####################################################################################
##########################    AFAD - Gnome - Tema   #########################################
#####################################################################################
#####################################################################################
#####################################################################################
##################  AFAD - DOMAIN Kurulumu  ###########################################
cp /opt/afad-gnome-tema/domainjoiner /usr/local/bin/
chmod 755 /usr/local/bin/domainjoiner
###########Dosya Yöneticisine Paylaşım kısayol ekleme###########
mkdir -p /etc/skel/.config/gtk-3.0
#mkdir -p /etc/skel/Masaüstü
mkdir -p /etc/skel/Şablonlar
cp -r /opt/afad-gnome-tema/etc/skel/.config/gtk-3.0/bookmarks /etc/skel/.config/gtk-3.0/
#cp -r /opt/afad-gnome-tema/etc/skel/Masaüstü/* /etc/skel/Masaüstü/
cp -r /opt/afad-gnome-tema/etc/skel/Şablonlar/* /etc/skel/Şablonlar/
#####################################################
#conf_file1=$(less /etc/skel/.config/gtk-3.0/bookmarks |grep paylas | wc -l)
#if [ "$conf_file1" == "0" ] ; then
#mkdir -p /etc/skel/.config/gtk-3.0
#cp -r /opt/afad-gnome-tema/.config/gtk-3.0/bookmarks /etc/skel/.config/gtk-3.0/
#else 
#echo ok
#fi


